//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFKostBackend.MonthPaidService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthPaidInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFKostService")]
    [System.SerializableAttribute()]
    public partial class MonthPaidInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoMonthPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KamarMonthPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TglMonthPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalMonthPaidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDTransaction {
            get {
                return this.IDTransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTransactionField, value) != true)) {
                    this.IDTransactionField = value;
                    this.RaisePropertyChanged("IDTransaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InfoMonthPaid {
            get {
                return this.InfoMonthPaidField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMonthPaidField, value) != true)) {
                    this.InfoMonthPaidField = value;
                    this.RaisePropertyChanged("InfoMonthPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KamarMonthPaid {
            get {
                return this.KamarMonthPaidField;
            }
            set {
                if ((object.ReferenceEquals(this.KamarMonthPaidField, value) != true)) {
                    this.KamarMonthPaidField = value;
                    this.RaisePropertyChanged("KamarMonthPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TglMonthPaid {
            get {
                return this.TglMonthPaidField;
            }
            set {
                if ((object.ReferenceEquals(this.TglMonthPaidField, value) != true)) {
                    this.TglMonthPaidField = value;
                    this.RaisePropertyChanged("TglMonthPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalMonthPaid {
            get {
                return this.TotalMonthPaidField;
            }
            set {
                if ((this.TotalMonthPaidField.Equals(value) != true)) {
                    this.TotalMonthPaidField = value;
                    this.RaisePropertyChanged("TotalMonthPaid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonthPaidService.IMonthPaidService")]
    public interface IMonthPaidService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonthPaidService/getMonthPaidByIDUser", ReplyAction="http://tempuri.org/IMonthPaidService/getMonthPaidByIDUserResponse")]
        WCFKostBackend.MonthPaidService.MonthPaidInfo[] getMonthPaidByIDUser(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonthPaidServiceChannel : WCFKostBackend.MonthPaidService.IMonthPaidService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonthPaidServiceClient : System.ServiceModel.ClientBase<WCFKostBackend.MonthPaidService.IMonthPaidService>, WCFKostBackend.MonthPaidService.IMonthPaidService {
        
        public MonthPaidServiceClient() {
        }
        
        public MonthPaidServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonthPaidServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonthPaidServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonthPaidServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFKostBackend.MonthPaidService.MonthPaidInfo[] getMonthPaidByIDUser(string id) {
            return base.Channel.getMonthPaidByIDUser(id);
        }
    }
}
