//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFKostBackend.AdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFKostService")]
    [System.SerializableAttribute()]
    public partial class AdminInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressAdmin {
            get {
                return this.AddressAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressAdminField, value) != true)) {
                    this.AddressAdminField = value;
                    this.RaisePropertyChanged("AddressAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDAdmin {
            get {
                return this.IDAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.IDAdminField, value) != true)) {
                    this.IDAdminField = value;
                    this.RaisePropertyChanged("IDAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAdmin {
            get {
                return this.NameAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.NameAdminField, value) != true)) {
                    this.NameAdminField = value;
                    this.RaisePropertyChanged("NameAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAdmin {
            get {
                return this.PasswordAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordAdminField, value) != true)) {
                    this.PasswordAdminField = value;
                    this.RaisePropertyChanged("PasswordAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumberAdmin {
            get {
                return this.PhoneNumberAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberAdminField, value) != true)) {
                    this.PhoneNumberAdminField = value;
                    this.RaisePropertyChanged("PhoneNumberAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeAdmin {
            get {
                return this.TypeAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeAdminField, value) != true)) {
                    this.TypeAdminField = value;
                    this.RaisePropertyChanged("TypeAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsernameAdmin {
            get {
                return this.UsernameAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameAdminField, value) != true)) {
                    this.UsernameAdminField = value;
                    this.RaisePropertyChanged("UsernameAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminService.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/loginAdmin", ReplyAction="http://tempuri.org/IAdminService/loginAdminResponse")]
        WCFKostBackend.AdminService.AdminInfo[] loginAdmin(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : WCFKostBackend.AdminService.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<WCFKostBackend.AdminService.IAdminService>, WCFKostBackend.AdminService.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFKostBackend.AdminService.AdminInfo[] loginAdmin(string username, string password) {
            return base.Channel.loginAdmin(username, password);
        }
    }
}
